### ISSUE TITLE
Broken layout

### ISSUE THREAD

**Issue by krzyzanowskim** [CocoaPods/cocoapods-docs#5]
I don't know if it's related strictly to Swift pods, or general issue, but somethimes layout is broken.

![screen shot 2015-01-26 at 21 26 51](https://cloud.githubusercontent.com/assets/758033/5907780/07f90e68-a5a2-11e4-9907-e747e096cd37.png)

http://cocoadocs.org/docsets/CryptoSwift/0.0.4/

**Comment by segiddins** [comment]
This belongs over on https://github.com/CocoaPods/cocoadocs.org
