### ISSUE TITLE
Doc is not generated for new pod

### ISSUE THREAD

**Issue by cezheng** [CocoaPods/cocoapods-docs#6]
Hi, I created my new pod yesterday but it seems to have some problems generating docs for it.

http://cocoadocs.org/docsets/Fuzi/0.1.0/

I have successfully generated docs locally using latest master branch of jazzy, any idea what the problem is?

btw, the header doc is in swift 2.0 format

**Comment by segiddins** [comment]
I don't think cocoadocs is yet running the swift 2 version of jazzy. Additionally, this issue belongs on the cocoadocs.org repo.
